# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    branches:
      only:
        - master

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run :
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
            sudo apt-get install -y jq
            sudo apt-get install -y moreutils

      - run:
          name: "Set Version Number"
          command: |
            echo 'export VERSION='$(jq -r '.version' dist/manifest.json) >> $BASH_ENV
            echo 'export BUILD_NUM'=$((CIRCLE_BUILD_NUM-14)) >> $BASH_ENV
            source $BASH_ENV
            jq '.version="'$VERSION.$BUILD_NUM'"' dist/manifest.json | sponge dist/manifest.json

      - run:
          name: "Build and Pack"
          command: |
            yarn install
            yarn qualitycheck
            yarn build
            git archive -o dist.zip HEAD dist

      - run:
          name: "Upload & Publish Extension to the Google Chrome Store"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T dist.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
            fi

      - store_artifacts:
          path: ./dist.zip

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
